### Pegar todas as artes
GET http://localhost:1234/arts

### Pegar uma arte por id
GET http://localhost:1234/arts/art-2

### Pegar todas as artes por uma categoria
GET http://localhost:1234/arts?categories=anime

### Criar uma arte com POST
POST http://localhost:1234/arts
Content-Type: application/json

{
  "sql": "SELECT * FROM users",
  "title": "The Test",
  "artist": "christopher",
  "date": "16/01/24",
  "art": "https://ciclovivo.com.br/wp-content/uploads/2018/10/iStock-536613027-1024x683.jpg",
  "categories": ["Ficção Científica", "Personagem"]
}

### Deletar uma arte
DELETE http://localhost:1234/arts/art-1

### Atualizar uma arte
PATCH http://localhost:1234/arts/art-3
Content-Type: application/json

{
  "artist": "Winnie Pooh"
}
